M48
; DRILL file {KiCad 8.0.5} date 2024-10-09T06:28:01+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-09T06:28:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
%
G90
G05
T1
X124.11Y-41.594
X129.89Y-41.594
T2
X141.752Y-38.354
X142.768Y-43.434
X143.784Y-38.354
M30
